version: '3.7'

services:     
  postgres:
    container_name: postgres-teplo
    hostname: postgres
    image: postgres:12.7
    environment:
      POSTGRES_PASSWORD: postgresroot
      POSTGRES_USER: postgres
      POSTGRES_DB: activity
    ports:
      - "0.0.0.0:5402:5432"

  frontend:
    build: ./activity
    ports:
      - 5401:5401